### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by deckard86** [mirumee/overv.io-beta#348]
Hello guys,

   after trying Over.io I can say it is fantastic. I have some suggestions for improve it:
- **Hot keys**: With Esc key, exit from new issue form or clear actual filter and send focus to text filter field. Also, a new hotkey for create a new issue and hotkeys for manage task. I think the best example of this is Trello (another fantastic app)
- If I use a workspace with various repositories and I delete one of them from github, Overv.io don't delete these issues from my workspace.
- I would like select repository icon color
- **Milestone management is awesome**
- In the issues context menu, I miss "set label". If I want change a label of an Issue, I have to open the "issues editor" and select it.
- I know a lot of people prefer markdown editor but it would be great add RTF editor. I think these tools can be used by non-developer personal (support, sellers,... ) and it would be fantastic an app that links development work with rest of team

It is all. Thanks for this fantastic tool. I can't wait for new features. 

Regards

pd. Excuse for my poor english :)

**Comment by mirekm** [comment]
Hi Ángel,

Thank you for the feedback and your kind words!
- In fact we support some basic **Hot keys** already — we've just added the **?** with a full list of all supported shortcuts. In brief:
  
  **c** → Compose a new issue in the preferred mode (see settings)
  **&lt;Shift&gt;** + **c** → Compose a new issue in the alternate mode
  **s** or **/** → Search
  **&lt;Ctrl&gt;** + **&lt;Enter&gt;** → Submit a new issue/comment/form
  
  We've just also extended **&lt;Escape&gt;** functionality in order to allow quitting from the filtering mode and either discarding a new issue (when there's no content to loose) or moving the focus to the trash icon (so the editor can be easily left).
- **Customisable repository color** — sounds good but we will have to give it some thought.
- **Set label** — good spot - sounds like a missing entry in this menu.
- Some additional support in terms of content editing (especially for non technical users) would be definitely nice to have and we will try to tackle it on some point in a near future.

Kind regards,
Mirek

**Comment by deckard86** [comment]
Excelent. Every day I like more and more your software :D
