### ISSUE TITLE
Board with multiple repos isn't displaying...

### ISSUE THREAD

**Issue by ehlersd** [mirumee/overv.io-beta#476]
https://overv.io/workspace/ehlersd/silly-worm/board/

I'm getting just a blank screen (except for the left-side menu, and the 2 little icons (upper right), and the "big blue" button (lower-right).

**Comment by mirekm** [comment]
Thanks for feedback Darren. We're looking into that. Will keep you posted.

**Comment by mirekm** [comment]
What browser and operating are you using?

**Comment by ehlersd** [comment]
Chrome on my Mac (Yosemite)
Version 41.0.2272.89 (64-bit)

**Comment by mirekm** [comment]
Thanks!

All good — we've found the problem and released appropriate patch so your board should work now on page refresh. However, we've also found that quick repositories filter (the grid next to the search input) requires additional effort since it only supports up to 4 repositories at the moment (and your project has 8 of them).

Thanks your your feedback!
