### ISSUE TITLE
Disable edit actions for users with read-only access

### ISSUE THREAD

**Issue by borekb** [mirumee/overv.io-beta#546]
We have a public repo where only a handful of users have write access. Still, when I visit the board as a public user, I seem to be able to do all sorts of "admin" actions like moving issues freely around, editing texts etc. Of course eventually, the action isn't really executed but the UI feels like I'm an admin even though I'm not.

**Comment by JanVoracek** [comment]
I think it's not executed only because GH API refuses the requests.

However, **everybody can change the overv.io project settings**. It means they can rename the board, change the target repository or even delete the board.

<img width="762" alt="screen shot 2016-04-08 at 12 35 58" src="https://cloud.githubusercontent.com/assets/703215/14381414/7f980d06-fd86-11e5-99fd-8be5dde08b20.png">

**Comment by mirekm** [comment]
Hi, we're working on the public boards at the moment. There are couple of known issues requiring ironing and this is one of them. We should be able to release an update still today. Sorry for the troubles.

**Comment by mirekm** [comment]
There was a bug affecting boards exclusively tracking only public repositories. We've just patched it and **only collaborators of all the repositories in a project can adjust its settings** now.
UI hasn't been updated yet but the _Settings_ button will be available only for the collaborators soon.
Thank you for the quick feedback and sorry for the troubles Jan.

**Comment by mirekm** [comment]
The sidebar buttons related to the collaborators only has been also removed. Thank you for the feedback @JanVoracek
